import { access, chmod, mkdir, readFile, rm, stat } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { atomicWrite, canonicalJson, readJson, removeEmptyDirectory, sha256 } from "./files.js";
import { buildGlobalDefinitionFiles, loadModels } from "./config.js";
import type { MrPaths } from "./paths.js";
import { InstallManifestSchema, SCHEMA_VERSION, type InstallManifest } from "./schema.js";

export interface InstallResult {
  readonly manifest: InstallManifest;
  readonly changedFiles: readonly string[];
}

export interface UninstallPlanEntry {
  readonly path: string;
  readonly action: "remove" | "preserve-modified" | "already-absent";
}

/**
 * Refreshes hashes for generated files already owned by the installer.
 * Model changes legitimately rewrite global agent definitions; keeping the
 * manifest in sync preserves safe upgrades and exact uninstall behavior.
 */
export async function refreshInstallManifestFiles(
  paths: MrPaths,
  files: ReadonlyMap<string, string>,
): Promise<void> {
  const manifest = await currentManifest(paths);
  if (manifest === undefined) return;
  const refreshed = manifest.files.map((owned) => {
    const content = files.get(owned.path);
    return content === undefined ? owned : { path: owned.path, sha256: sha256(content) };
  });
  await atomicWrite(paths.manifest, canonicalJson({ ...manifest, files: refreshed }));
}

async function currentManifest(paths: MrPaths): Promise<InstallManifest | undefined> {
  try {
    return await loadManifest(paths);
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return undefined;
    }
    throw error;
  }
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

function executable(runtime: string, script: string, subcommand?: string): string {
  const command = subcommand === undefined ? "" : ` ${subcommand}`;
  return `#!/bin/sh\nset -eu\nexec ${shellQuote(runtime)} ${shellQuote(script)}${command} "$@"\n`;
}

function bunExecutable(runtime: string): string {
  return `#!/bin/sh\nset -eu\nexec ${shellQuote(runtime)} "$@"\n`;
}

/**
 * Global OpenCode loader plugin. Auto-discovered from ~/.config/opencode/plugins/.
 * When a plain `opencode` session starts inside a registered mr-orchestrator
 * workspace, it merges the generated config (agents + commands) via the
 * `config` hook and delegates tools to the generated plugin. No-op elsewhere.
 */
function loaderPlugin(): string {
  return `// Generated by mr-orchestrator install. Do not edit (owned by install-manifest).
import { readFile } from "node:fs/promises";
import { existsSync, realpathSync } from "node:fs";
import { join, resolve } from "node:path";
import { homedir } from "node:os";
import { pathToFileURL } from "node:url";

export const MrOrchestratorLoader = async (ctx) => {
  // mrcode already injects the full generated config; avoid double registration.
  if ((process.env.OPENCODE_CONFIG ?? "").includes("mr-orchestrator/generated")) return {};
  try {
    const configRoot = join(process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config"), "mr-orchestrator");
    const registryPath = join(configRoot, "workspaces.json");
    if (!existsSync(registryPath)) return {};
    const registry = JSON.parse(await readFile(registryPath, "utf8"));
    let cwd = resolve(ctx.directory);
    try { cwd = realpathSync(cwd); } catch {}
    const workspace = (registry.workspaces ?? [])
      .filter((w) => cwd === w.root || cwd.startsWith(w.root + "/"))
      .sort((a, b) => b.root.length - a.root.length)[0];
    if (workspace === undefined) return {};
    const generatedDir = join(configRoot, "generated", workspace.id);
    const mrConfig = JSON.parse(await readFile(join(generatedDir, "opencode.mr.json"), "utf8"));
    const module = await import(pathToFileURL(join(generatedDir, "plugin.js")).href);
    const pluginFn = module.MrOrchestrator ?? Object.values(module)[0];
    const hooks = typeof pluginFn === "function" ? await pluginFn(ctx) : {};
    return {
      ...hooks,
      config: async (input) => {
        input.command = { ...(mrConfig.command ?? {}), ...(input.command ?? {}) };
        input.agent = { ...(mrConfig.agent ?? {}), ...(input.agent ?? {}) };
        if (mrConfig.default_agent !== undefined) input.default_agent = mrConfig.default_agent;
      },
    };
  } catch (err) {
    // Surface loader failures instead of silently swallowing them.
    // This runs inside OpenCode; write to stderr so it shows in the TUI log.
    process.stderr.write(
      \`[mr-orchestrator-loader] Failed to load plugin for \${ctx?.directory ?? "unknown"}: \${err?.message ?? err}\\n\`
    );
    return {};
  }
};
`;
}

export async function install(paths: MrPaths, sourceRoot: string, version: string): Promise<InstallResult> {
  const source = resolve(sourceRoot);
  const cli = join(source, "dist", "src", "cli.js");
  await access(cli);
  await access(paths.bunBinary);
  const files = new Map<string, string>([
    [join(paths.binRoot, "mr"), executable(paths.bunBinary, cli)],
    [join(paths.binRoot, "mrcode"), executable(paths.bunBinary, cli, "launch")],
    [join(paths.binRoot, "bun"), bunExecutable(paths.bunBinary)],
    [join(paths.opencodePluginsRoot, "mr-orchestrator-loader.ts"), loaderPlugin()],
  ]);
  const models = await loadModels(paths);
  for (const [path, content] of buildGlobalDefinitionFiles(paths, models)) {
    files.set(path, content);
  }
  const changedFiles: string[] = [];
  const previousManifest = await currentManifest(paths);

  for (const [path, content] of files) {
    try {
      const previous = await readFile(path, "utf8");
      if (previous !== content) {
        const previousOwnership = previousManifest?.files.find((item) => item.path === path);
        if (previousOwnership === undefined || sha256(previous) !== previousOwnership.sha256) {
          throw new Error(`Refusing to overwrite unowned or modified file: ${path}`);
        }
      }
    } catch (error: unknown) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
        throw error;
      }
    }
  }

  await mkdir(paths.binRoot, { recursive: true });
  await mkdir(paths.opencodePluginsRoot, { recursive: true });
  await mkdir(paths.opencodeAgentsRoot, { recursive: true });
  await mkdir(paths.opencodeCommandsRoot, { recursive: true });

  for (const [path, content] of files) {
    let previous: string | undefined;
    try {
      previous = await readFile(path, "utf8");
    } catch (error: unknown) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
        throw error;
      }
    }
    if (previous !== content) {
      await atomicWrite(path, content, 0o755);
      await chmod(path, 0o755);
      changedFiles.push(path);
    }
  }

  const manifest: InstallManifest = {
    schemaVersion: SCHEMA_VERSION,
    version,
    installedAt: new Date().toISOString(),
    sourceRoot: source,
    files: [...files.entries()].map(([path, content]) => ({ path, sha256: sha256(content) })),
  };
  await atomicWrite(paths.manifest, canonicalJson(manifest));
  return { manifest, changedFiles };
}

export async function loadManifest(paths: MrPaths): Promise<InstallManifest> {
  return readJson(paths.manifest, InstallManifestSchema);
}

export async function planUninstall(paths: MrPaths): Promise<readonly UninstallPlanEntry[]> {
  const manifest = await loadManifest(paths);
  const files = await Promise.all(
    manifest.files.map(async (owned): Promise<UninstallPlanEntry> => {
      try {
        const content = await readFile(owned.path);
        return { path: owned.path, action: sha256(content) === owned.sha256 ? "remove" : "preserve-modified" };
      } catch (error: unknown) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") {
          return { path: owned.path, action: "already-absent" };
        }
        throw error;
      }
    }),
  );
  return files;
}

export async function uninstall(paths: MrPaths, purge: boolean): Promise<readonly UninstallPlanEntry[]> {
  const plan = await planUninstall(paths);
  for (const item of plan) {
    if (item.action === "remove") {
      await rm(item.path);
      await removeEmptyDirectory(dirname(item.path));
    }
  }
  await rm(paths.manifest);

  if (purge) {
    await rm(paths.configRoot, { recursive: true, force: true });
    await rm(paths.dataRoot, { recursive: true, force: true });
    await rm(paths.cacheRoot, { recursive: true, force: true });
  }
  return plan;
}

export async function pathExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return false;
    }
    throw error;
  }
}
