import { readFile, writeFile, mkdir, copyFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { existsSync } from "node:fs";
import type { MrPaths } from "./paths.js";
import { loadRegistry, saveRegistry } from "./workspace.js";
import type { WorkspaceRegistry } from "./schema.js";
import { loadModels } from "./config.js";
import { MigrationRegistry } from "./flow-schema.js";
import { atomicWrite, canonicalJson, readJson } from "./files.js";
import { InstallManifestSchema, type InstallManifest } from "./schema.js";

// ─── Update & Migration ──────────────────────────────────────────────────────

export interface UpdatePlan {
  readonly fromVersion: string;
  readonly toVersion: string;
  readonly migrations: readonly string[];
  readonly backupPath: string;
  readonly rollbackPath: string;
}

export interface ProfileExport {
  readonly schemaVersion: 1;
  readonly exportedAt: string;
  readonly version: string;
  readonly registry: WorkspaceRegistry;
  readonly models: unknown;
  readonly manifest: InstallManifest;
}

export async function createBackup(paths: MrPaths): Promise<string> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupDir = join(paths.dataRoot, "backups", timestamp);
  await mkdir(backupDir, { recursive: true });

  // Backup critical files
  const filesToBackup = [
    paths.registry,
    paths.models,
    paths.manifest,
  ];

  for (const file of filesToBackup) {
    if (existsSync(file)) {
      const dest = join(backupDir, file.split("/").pop() ?? "backup.json");
      await copyFile(file, dest);
    }
  }

  return backupDir;
}

export async function restoreBackup(paths: MrPaths, backupDir: string): Promise<void> {
  const files = [
    { src: join(backupDir, "workspaces.json"), dest: paths.registry },
    { src: join(backupDir, "models.json"), dest: paths.models },
    { src: join(backupDir, "install-manifest.json"), dest: paths.manifest },
  ];

  for (const { src, dest } of files) {
    if (existsSync(src)) {
      await mkdir(dirname(dest), { recursive: true });
      await copyFile(src, dest);
    }
  }
}

export async function planUpdate(paths: MrPaths, targetVersion: string): Promise<UpdatePlan> {
  const manifest = await readJson(paths.manifest, InstallManifestSchema);
  const fromVersion = manifest.version;

  const backupPath = await createBackup(paths);
  const rollbackPath = join(backupPath, "rollback.sh");

  // Generate rollback script
  const rollbackScript = `#!/bin/sh
# Rollback script generated by mr-orchestrator
# Restores state from ${backupDir(backupPath)}
set -eu
cp "${join(backupPath, "workspaces.json")}" "${paths.registry}"
cp "${join(backupPath, "models.json")}" "${paths.models}"
cp "${join(backupPath, "install-manifest.json")}" "${paths.manifest}"
echo "Rollback complete to version ${fromVersion}"
`;
  await writeFile(rollbackPath, rollbackScript, { mode: 0o755 });

  // Determine migrations needed
  const migrations: string[] = [];
  const currentMajor = parseInt(fromVersion.split(".")[0] ?? "0", 10);
  const targetMajor = parseInt(targetVersion.split(".")[0] ?? "0", 10);

  for (let v = currentMajor; v < targetMajor; v++) {
    migrations.push(`migrate-v${v}-to-v${v + 1}`);
  }

  return {
    fromVersion,
    toVersion: targetVersion,
    migrations,
    backupPath,
    rollbackPath,
  };
}

export async function executeUpdate(paths: MrPaths, plan: UpdatePlan): Promise<void> {
  // Run migrations (registry reserved for future schema migrations)
  const _registry = new MigrationRegistry();

  // Register built-in migrations here
  // _registry.register({ fromVersion: 1, toVersion: 2, migrate: (s) => ({ ...s, schemaVersion: 2 }) });

  // Update manifest version
  const manifest = await readJson(paths.manifest, InstallManifestSchema);
  const updated: InstallManifest = {
    ...manifest,
    version: plan.toVersion,
  };
  await atomicWrite(paths.manifest, canonicalJson(updated));
}

export async function executeRollback(paths: MrPaths, backupPath: string): Promise<void> {
  await restoreBackup(paths, backupPath);
}

function backupDir(path: string): string {
  return path.split("/").slice(-2).join("/");
}

// ─── Profile Export/Import ───────────────────────────────────────────────────

export async function exportProfile(paths: MrPaths): Promise<string> {
  const registry = await loadRegistry(paths);
  const models = await loadModels(paths);
  const manifest = await readJson(paths.manifest, InstallManifestSchema);

  const profile: ProfileExport = {
    schemaVersion: 1,
    exportedAt: new Date().toISOString(),
    version: manifest.version,
    registry,
    models,
    manifest,
  };

  const exportDir = join(paths.dataRoot, "exports");
  await mkdir(exportDir, { recursive: true });
  const filename = `mr-profile-${new Date().toISOString().replace(/[:.]/g, "-")}.json`;
  const filepath = join(exportDir, filename);
  await writeFile(filepath, JSON.stringify(profile, null, 2));
  return filepath;
}

export async function importProfile(paths: MrPaths, filepath: string): Promise<void> {
  const content = await readFile(filepath, "utf8");
  const profile = JSON.parse(content) as ProfileExport;

  if (profile.schemaVersion !== 1) {
    throw new Error(`Unsupported profile version: ${profile.schemaVersion}`);
  }

  // Create backup before import
  await createBackup(paths);

  // Restore registry
  await saveRegistry(paths, profile.registry);

  // Restore models
  const { saveModels } = await import("./models.js");
  await saveModels(paths, profile.models as never);

  // Restore manifest
  await atomicWrite(paths.manifest, canonicalJson(profile.manifest));
}

// ─── GitLab Adapter (F8) ─────────────────────────────────────────────────────

export class GitLabAdapter {
  constructor(private readonly token?: string) {}

  async createMergeRequest(
    projectId: string,
    sourceBranch: string,
    targetBranch: string,
    _title: string,
    _description: string,
  ): Promise<string> {
    // GitLab API stub
    return `https://gitlab.com/${projectId}/-/merge_requests/new?merge_request[source_branch]=${sourceBranch}&merge_request[target_branch]=${targetBranch}`;
  }

  async getIssue(projectId: string, issueId: string): Promise<{ title: string; description: string }> {
    // GitLab API stub
    return {
      title: `[GitLab ${projectId}#${issueId}]`,
      description: "GitLab integration not yet fully implemented",
    };
  }
}

// ─── Multi-Platform Detection ────────────────────────────────────────────────

export type Platform = "github" | "gitlab" | "bitbucket" | "unknown";

export function detectPlatform(remoteUrl: string): Platform {
  if (remoteUrl.includes("github.com")) return "github";
  if (remoteUrl.includes("gitlab.com")) return "gitlab";
  if (remoteUrl.includes("bitbucket.org")) return "bitbucket";
  return "unknown";
}

export async function getWorkspacePlatform(root: string): Promise<Platform> {
  const { runCommand } = await import("./process.js");
  const result = runCommand("git", ["-C", root, "remote", "get-url", "origin"]);
  if (!result.ok) return "unknown";
  return detectPlatform(result.stdout.trim());
}
