import type { DeveloperPreference, RepositoryRules, WorkspaceRules } from "./generator.js";
import type { RepositoryProfile } from "./profiler.js";

export type AgentsLanguage = "en" | "es";

const PREFERENCES: Record<AgentsLanguage, Record<DeveloperPreference, string>> = {
  en: {
    "minimal-reversible-changes": "Make the smallest coherent, reversible change.",
    "strict-typing": "Preserve strict typing; never introduce `any`.",
    "tests-with-behavior-changes": "Add or update tests with every behavior change.",
    "allow-justified-local-refactors": "Local refactors are allowed when justified and in scope.",
    "no-new-dependencies-without-reason": "Do not add dependencies without stating why.",
    "explicit-over-abstract": "Prefer explicit code over premature abstractions.",
    "ask-before-architecture-changes": "Ask before irreversible architectural changes.",
  },
  es: {
    "minimal-reversible-changes": "Haz el cambio coherente y reversible más pequeño posible.",
    "strict-typing": "Conserva el tipado estricto; no introduzcas `any`.",
    "tests-with-behavior-changes": "Añade o actualiza tests con cada cambio de comportamiento.",
    "allow-justified-local-refactors": "Se permiten refactors locales justificados y dentro del alcance.",
    "no-new-dependencies-without-reason": "No añadas dependencias sin explicar el motivo.",
    "explicit-over-abstract": "Prefiere código explícito a abstracciones prematuras.",
    "ask-before-architecture-changes": "Pregunta antes de cambios arquitectónicos irreversibles.",
  },
};

const TEXT = {
  en: {
    title: "Workspace Rules", source: "Generated by `mr atlas init`. Source of truth: `.aicontext/atlas/rules.json`.",
    work: "How agents should work here", repo: "Repository", repos: "Repositories", role: "Role", stack: "Stack", rules: "Rules",
    agentRules: "Agent Rules", commands: "Commands", conventions: "Conventions (current state)", how: "How to work",
    critical: "Critical areas", review: "Review carefully", unknown: "Unknown", inferred: "inferred", layout: "oriented layout under",
  },
  es: {
    title: "Reglas del workspace", source: "Generado por `mr atlas init`. Fuente de verdad: `.aicontext/atlas/rules.json`.",
    work: "Cómo deben trabajar aquí los agentes", repo: "Repositorio", repos: "Repositorios", role: "Rol", stack: "Stack", rules: "Reglas",
    agentRules: "Reglas para agentes", commands: "Comandos", conventions: "Convenciones (estado actual)", how: "Cómo trabajar",
    critical: "Áreas críticas", review: "Revisar con cuidado", unknown: "Desconocido", inferred: "inferida", layout: "con estructura orientada a",
  },
} as const;

export function renderWorkspaceAgentsMarkdown(rules: WorkspaceRules, profiles: readonly RepositoryProfile[], language: AgentsLanguage = "en"): string {
  const text = TEXT[language];
  const byRepo = new Map(profiles.map((profile) => [profile.repo, profile]));
  return [
    `# ${text.title}`, "", text.source, "", `## ${text.work}`,
    ...rules.preferences.map((preference) => `- ${PREFERENCES[language][preference]}`),
    "", `## ${text.repos}`, `| ${text.repo} | ${text.role} | ${text.stack} | ${text.rules} |`, "|---|---|---|---|",
    ...rules.repositories.map((repository) => {
      const profile = byRepo.get(repository.repo);
      const frameworks = profile?.stack.frameworks.join(", ") ?? "";
      const languages = profile?.stack.languages.join(", ") ?? "";
      const stack = frameworks.length > 0 ? frameworks : languages.length > 0 ? languages : "unknown";
      return `| ${repository.repo} | ${profile?.kind ?? "unknown"} | ${stack} | \`.aicontext/atlas/repos/${repository.repo}/AGENTS.md\` |`;
    }), "",
  ].join("\n");
}

export function renderRepositoryAgentsMarkdown(rules: RepositoryRules, profile: RepositoryProfile, preferences: readonly DeveloperPreference[], language: AgentsLanguage = "en"): string {
  const text = TEXT[language];
  const commands = Object.entries(profile.commands).map(([name, value]) => `- ${name}: \`${value}\``);
  const conventionRules = rules.rules.filter((rule) => !rule.id.startsWith("commands.")).map((rule) => `- ${rule.statement}${rule.kind === "inferred" ? ` *(${text.inferred})*` : ""}`);
  return [
    `# ${profile.repo} — ${text.agentRules}`, "", `## ${text.role}`,
    `${profile.kind}; ${profile.layout.style} ${text.layout} ${profile.layout.roots.map((root) => `\`${root}\``).join(", ") || "the repository root"}.`, "",
    ...(commands.length === 0 ? [] : [`## ${text.commands}`, ...commands, ""]),
    `## ${text.conventions}`, ...conventionRules, "", `## ${text.how}`, ...preferences.map((preference) => `- ${PREFERENCES[language][preference]}`), "",
    ...(profile.criticalAreas.length === 0 ? [] : [`## ${text.critical}`, `- ${text.review}: ${profile.criticalAreas.join(", ")}.`, ""]),
    ...(profile.gaps.length === 0 ? [] : [`## ${text.unknown}`, ...profile.gaps.map((gap) => `- ${gap}`), ""]),
  ].join("\n");
}

export function renderAgentsMarkdown(profile: RepositoryProfile, rules: RepositoryRules, language: AgentsLanguage = "en", preferences: readonly DeveloperPreference[] = []): string {
  return renderRepositoryAgentsMarkdown(rules, profile, preferences, language);
}

export function renderRulesDiff(previous: string | undefined, next: string): string {
  if (previous === next) return "No changes.";
  if (previous === undefined) return next.split("\n").map((line) => `+ ${line}`).join("\n");
  const before = new Set(previous.split("\n"));
  const after = new Set(next.split("\n"));
  return [
    ...previous.split("\n").filter((line) => !after.has(line)).map((line) => `- ${line}`),
    ...next.split("\n").filter((line) => !before.has(line)).map((line) => `+ ${line}`),
  ].join("\n") || "Content changed.";
}
